name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  firebase_database: ^9.0.4
  universal_html: ^2.0.8
  syncfusion_flutter_datepicker: ^20.1.47
  photo_view: ^0.13.0
  firebase_storage: ^10.2.10
  path_provider: ^2.0.9
  cloud_firestore_platform_interface: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
