// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpX5gNXalix2wQAEGYSvOzdrvxBU4bK8M',
    appId: '1:49279927621:web:3987404a89b50b684fea2c',
    messagingSenderId: '49279927621',
    projectId: 'papipe-f7cd8',
    authDomain: 'papipe-f7cd8.firebaseapp.com',
    databaseURL: 'https://papipe-f7cd8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'papipe-f7cd8.appspot.com',
    measurementId: 'G-PVSB24FZHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMJ0QpXiOx6H0KZI7UCPH5GRvpH9Ren8',
    appId: '1:49279927621:android:9cf6cd7e24363ecf4fea2c',
    messagingSenderId: '49279927621',
    projectId: 'papipe-f7cd8',
    databaseURL: 'https://papipe-f7cd8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'papipe-f7cd8.appspot.com',
  );
}
